#include "mvlc_trigger_io_serialize_vmescript.h"

#include <cstdlib>
#include <sstream>
#include <yaml-cpp/yaml.h>

#include <mesytec-mvlc/mvlc_trigger_io_deserialize.h>
#include <mesytec-mvlc/mvlc_trigger_io_serialize.h>
#include <mesytec-mvlc/util/fmt.h>
#include <mesytec-mvlc/util/overloaded.h>
#include <mesytec-mvlc/util/string_util.h>

using namespace mesytec::mvlc;

namespace mesytec::mvlc::trigger_io
{

static const char *TriggerIoMvmeMinVersion = "1.9.1";

static const std::string MetaBlockBegin = "meta_block_begin";
static const std::string MetaBlockEnd = "meta_block_end";
static const std::string MetaTagMVLCTriggerIO = "mvlc_trigger_io";
static const std::string MVLCStackBegin = "mvlc_stack_begin";
static const std::string MVLCStackEnd = "mvlc_stack_end";

struct VMEScriptGenerator: public IScriptPartVisitor
{
    std::ostringstream oss;

    std::string format_register_write(const RegisterWrite &write)
    {
        std::string line = fmt::format("  0x{:04x} ", write.address);

        if (write.options & RegisterWrite::Opt_HexValue)
        {
            line += fmt::format("0x{:04x}", write.value);
        }
        else if (write.options & RegisterWrite::Opt_BinValue)
        {
            line += fmt::format("0b{:04b}", write.value);
        }
        else
        {
            line += fmt::format("  {:4}", write.value);
        }

        if (!write.comment.empty())
        {
            line += "    # " + write.comment;
        }

        return line;
    }

    void operator()(const RegisterWrite &write) override
    {
        oss << format_register_write(write) << "\n";
    }

    void operator()(const std::string &blockComment) override
    {
        if (!blockComment.empty())
        {
            oss << "\n# " << blockComment << "\n";
        }
    }

    void operator()(const UnitBlock &ub) override
    {
        oss << "\n# " << ub.comment << "\n";

        oss << MVLCStackBegin << "\n";

        for (const auto &part: ub.parts)
        {
            // clang-format off
            std::visit(mesytec::mvlc::util::overloaded {
                [this](const RegisterWrite &write)
                {
                    this->operator()(write);
                },
                [this](const std::string &comment)
                {
                    oss << "  # " << comment << "\n";
                }
            }, part);
            // clang-format on
        }

        oss << MVLCStackEnd << "\n";
    }

    ~VMEScriptGenerator() override = default;
};

std::string generate_trigger_io_vmescript(const TriggerIO &ioCfg)
{
    // clang-format off
    std::vector<std::string> intro
    {
        "##############################################################",
        "# MVLC Trigger I/O  setup via internal VME interface         #",
        "##############################################################",
        "",
        "# Note: This file was generated by mvme. Editing existing",
        "# values is allowed and these changes will be used by mvme",
        "# when next parsing the script. Changes to the basic",
        "# structure, like adding new write or read commands, are not",
        "# allowed. These changes will be lost the next time the file",
        "# is modified by mvme.",
        "",
        "# The initialization commands for each Trigger I/O unit are",
        "# wrapped in mvlc_stack_begin/end blocks. This is to ensure",
        "# the commands are executed atomically without being",
        "# interleaved by other commands also touching the Trigger I/O",
        "# system, e.g. the routine for readout of the builtin DSO.",
        "",
        "# Check for minimum required mvme version",
        fmt::format("mvme_require_version {}", TriggerIoMvmeMinVersion).c_str(),
        "",
        "# Internal MVLC VME interface address",
        fmt::format("setbase 0x{:08x}", SelfVMEAddress).c_str()
    };
    // clang-format on

    VMEScriptGenerator gen;
    std::copy(intro.begin(), intro.end(), std::ostream_iterator<std::string>(gen.oss, "\n"));

    visit(generate_trigger_io_parts(ioCfg), gen);

    // clang-format off
    std::vector<std::string> metalines
    {
        "",
        "##############################################################",
        "# MVLC Trigger I/O specific meta information                 #",
        "##############################################################",
        MetaBlockBegin + " " + MetaTagMVLCTriggerIO,
        generate_meta_info_yaml(ioCfg),
        MetaBlockEnd
    };
    // clang-format on

    std::copy(metalines.begin(), metalines.end(),
              std::ostream_iterator<std::string>(gen.oss, "\n"));

    return gen.oss.str();
}

template <typename T> T parse_binary(std::string_view input)
{
    const size_t maxShift = (sizeof(T) * 8) - 1;

    size_t shift = 0;
    T result = 0;

    for (s32 i = input.size() - 1; i >= 0; --i)
    {
        char c = input.at(i);

        switch (c)
        {
        case '0':
        case '1':
            if (shift > maxShift)
                throw std::out_of_range("binary numeric input value too large");

            result |= ((c - '0') << shift++);
            break;

        // Skip the digit separators
        case '\'':
            break;

        default:
            throw std::invalid_argument("invalid character in binary literal");
        }
    }

    return result;
}

template <typename T> T parse_numeric(std::string_view str)
{
    constexpr auto maxValue = std::numeric_limits<T>::max();
    T value = {};

    if (util::startswith(str, "0b") || util::startswith(str, "0B"))
    {
        value = parse_binary<T>(str.substr(2));
    }
    else
    {
        value = std::strtoull(str.data(), nullptr, 0);
    }

    if (value > maxValue)
        throw std::runtime_error(fmt::format(
            "parsed numeric value '{}' is out of range (maxValue={})", value, maxValue));

    return static_cast<T>(value);
}

TriggerIO parse_trigger_io_vmescript(const std::string &text)
{
    // Flat list of writes we build from the parsed VMEScript plus the meta info
    // block contents. This is filled out and passed on to deserialize_trigger_io().
    std::vector<WriteCommand> writes;
    std::string metaYaml;

    std::istringstream iss(text);
    std::string line;
    unsigned lineNumber = 1;

    while (std::getline(iss, line))
    {
        if (line.empty() || line[0] == '#')
            continue;

        // Check for the start of the meta info block.
        if (util::startswith(line, MetaBlockBegin + " " + MetaTagMVLCTriggerIO))
        {
            while (std::getline(iss, line))
            {
                if (util::startswith(line, MetaBlockEnd))
                    break;

                metaYaml += line + "\n";
            }
        }
        // Otherwise try to interpret the line as a write command.
        else
        {
            // Check if the line has at least two parts: address and value.
            std::istringstream lineIss(line);
            std::string addressStr;
            std::string valueStr;
            if (lineIss >> addressStr >> valueStr)
            {
                u16 address = 0;

                try
                {
                    address = parse_numeric<u16>(addressStr);
                }
                catch (const std::exception &e)
                {
                    throw std::runtime_error(
                        fmt::format("Error parsing address on line {}: {}", lineNumber, e.what()));
                }

                u16 value = 0;

                try
                {
                    value = parse_numeric<u16>(valueStr);
                }
                catch (const std::exception &e)
                {
                    throw std::runtime_error(
                        fmt::format("Error parsing value on line {}: {}", lineNumber, e.what()));
                }

                writes.push_back(WriteCommand{address, value});
            }
        }
        ++lineNumber;
    }

    return deserialize_trigger_io(writes, metaYaml);
}

} // namespace mesytec::mvlc::trigger_io
