#include "mvlc_trigger_io_serialize_vmescript.h"

#include <sstream>

#include <mesytec-mvlc/mvlc_trigger_io_serialize.h>
#include <mesytec-mvlc/util/fmt.h>
#include <mesytec-mvlc/util/overloaded.h>

using namespace mesytec::mvlc;

namespace mesytec::mvlc::trigger_io
{
    static const char *TriggerIoMvmeMinVersion = "1.9.1";

    struct VMEScriptGenerator: public IScriptPartVisitor
    {
        std::ostringstream oss;

        std::string format_register_write(const RegisterWrite &write)
        {
            std::string line = fmt::format("  0x{:04x} ", write.address);

            if (write.options & RegisterWrite::Opt_HexValue)
            {
                line += fmt::format("0x{:04x}", write.value);
            }
            else if (write.options & RegisterWrite::Opt_BinValue)
            {
                line += fmt::format("0b{:04b}", write.value);
            }
            else
            {
                line += fmt::format("  {:4}", write.value);
            }

            if (!write.comment.empty())
            {
                line += "    # " + write.comment;
            }

            return line;
        }

        void operator()(const RegisterWrite &write) override
        {
            oss << format_register_write(write) << "\n";
        }

        void operator()(const std::string &blockComment) override
        {
            if (!blockComment.empty())
            {
                oss << "\n# " << blockComment << "\n";
            }
        }

        void operator()(const UnitBlock &ub) override
        {
            oss << "\n# " << ub.comment << "\n";

            oss << "mvlc_stack_begin\n";

            for (const auto &part: ub.parts)
            {
                std::visit(mesytec::mvlc::util::overloaded {
                    [this](const RegisterWrite &write)
                    {
                        this->operator()(write);
                    },
                    [this](const std::string &comment)
                    {
                        oss << "  # " << comment << "\n";
                    }
                }, part);
            }

            oss << "mvlc_stack_end\n";
        }

        ~VMEScriptGenerator() override = default;
    };


static const std::string MetaBlockBegin = "meta_block_begin";
static const std::string MetaBlockEnd = "meta_block_end";
static const std::string MetaTagMVLCTriggerIO = "mvlc_trigger_io";


std::string generate_trigger_io_vmescript(const TriggerIO &ioCfg)
{
    std::vector<std::string> intro
    {
        "##############################################################",
        "# MVLC Trigger I/O  setup via internal VME interface         #",
        "##############################################################",
        "",
        "# Note: This file was generated by mvme. Editing existing",
        "# values is allowed and these changes will be used by mvme",
        "# when next parsing the script. Changes to the basic",
        "# structure, like adding new write or read commands, are not",
        "# allowed. These changes will be lost the next time the file",
        "# is modified by mvme.",
        "",
        "# The initialization commands for each Trigger I/O unit are",
        "# wrapped in mvlc_stack_begin/end blocks. This is to ensure",
        "# the commands are executed atomically without being",
        "# interleaved by other commands also touching the Trigger I/O",
        "# system, e.g. the routine for readout of the builtin DSO.",
        "",
        "# Check for minimum required mvme version",
        fmt::format("mvme_require_version {}", TriggerIoMvmeMinVersion).c_str(),
        "",
        "# Internal MVLC VME interface address",
        fmt::format("setbase 0x{:08x}", SelfVMEAddress).c_str()
    };

    VMEScriptGenerator gen;
    std::copy(intro.begin(), intro.end(),
              std::ostream_iterator<std::string>(gen.oss, "\n"));

    visit(generate_trigger_io_parts(ioCfg), gen);


    std::vector<std::string> metalines
    {
        "",
        "##############################################################",
        "# MVLC Trigger I/O specific meta information                 #",
        "##############################################################",
        MetaBlockBegin + " " + MetaTagMVLCTriggerIO,
        generate_meta_info_yaml(ioCfg),
        MetaBlockEnd
    };

    std::copy(metalines.begin(), metalines.end(),
              std::ostream_iterator<std::string>(gen.oss, "\n"));

    return gen.oss.str();
}

TriggerIO parse_trigger_io_vmescript(const std::string &text)
{
    return {};
}

}
