#include <mesytec-mvlc/mvlc_trigger_io_serialize_internal.h>
#include <mesytec-mvlc/util/fmt.h>

using namespace mesytec::mvlc::trigger_io;

// Source: perplexity.ai
std::string escape_underscores(std::string s)
{
    for (std::size_t pos = 0; (pos = s.find('_', pos)) != std::string::npos;)
    {
        s.insert(pos, "\\"); // insert backslash before '_'
        pos += 2;            // skip over the newly inserted "\_"
    }
    return s;
}

std::string make_coldef(size_t columns)
{
    std::string coldef = "|";
    for (int i = 0; i < columns; ++i)
    {
        coldef += "l|";
    }
    return coldef;
}

void print_table_header(std::ostream &oss, const std::string &caption,
                        std::vector<std::string> columnTitles = {"Register", "Description"})
{
    fmt::println(oss, "\\begin{{table}}[H]");
    fmt::println(oss, "    \\centering");
    fmt::println(oss, "    \\caption{{{}}}", caption);
    fmt::println(oss, "    \\begin{{tabular}}{{{}}}", make_coldef(columnTitles.size()));
    fmt::print(oss, "        \\hline");

    std::vector<std::string> formattedColumnTitles;

    for (const auto &title: columnTitles)
    {
        formattedColumnTitles.push_back(fmt::format("\\textbf{{{}}}", title));
    }

    fmt::println(oss, " {} \\\\", fmt::join(formattedColumnTitles, " & "));
}

void print_table_footer(std::ostream &oss)
{
    fmt::println(oss, "        \\hline");
    fmt::println(oss, "    \\end{{tabular}}");
    fmt::println(oss, "\\end{{table}}");
    fmt::println(oss, "");
}

void print_table_contents(std::ostream &oss, const BasicParts &parts)
{
    for (const auto &part: parts)
    {
        if (auto regWrite = std::get_if<RegisterWrite>(&part))
        {
            fmt::println(oss, "        \\hline 0x{:04X} & {}\\\\", regWrite->address,
                         escape_underscores(regWrite->comment));
        }
    }
}

void gen_timer_table(std::ostream &oss)
{
    auto parts = generate(Timer{}, 0);

    print_table_header(oss, "Timer properties");
    print_table_contents(oss, parts);
    print_table_footer(oss);
}

void gen_nim_io_table(std::ostream &oss)
{
    auto parts = generate(IO{}, io_flags::NIM_IO_Flags, 0);

    print_table_header(oss, "NIM IO properties");
    print_table_contents(oss, parts);
    print_table_footer(oss);
}

void gen_ecl_io_table(std::ostream &oss)
{
    auto parts = generate(IO{}, io_flags::ECL_IO_Flags, 0);

    print_table_header(oss, "ECL IO properties");
    print_table_contents(oss, parts);
    print_table_footer(oss);
}

void gen_trigger_resource_table(std::ostream &oss)
{
    auto parts = generate(TriggerResource{}, 0);

    print_table_header(oss, "Trigger Resource properties");
    print_table_contents(oss, parts);
    print_table_footer(oss);
}

void gen_stackbusy_table(std::ostream &oss)
{
    auto parts = generate(StackBusy{}, 0);

    print_table_header(oss, "Stack Busy properties");
    print_table_contents(oss, parts);
    print_table_footer(oss);
}

void gen_lut_table(std::ostream &oss)
{
    auto parts = write_lut(LUT{});

    print_table_header(oss, "LUT properties");
    print_table_contents(oss, parts);
    print_table_footer(oss);
}

void gen_stackstart_table(std::ostream &oss)
{
    auto parts = generate(StackStart{}, 0);

    print_table_header(oss, "Stack Start properties");
    print_table_contents(oss, parts);
    print_table_footer(oss);
}

// This is for the 'MasterTrigger' structure. It is going to be refactored.
void gen_synctrigger_table(std::ostream &oss)
{
    auto parts = generate(MasterTrigger{}, 0);

    print_table_header(oss, "Sync Trigger properties");
    print_table_contents(oss, parts);
    print_table_footer(oss);
}

void gen_counter_table(std::ostream &oss)
{
    auto parts = generate(Counter{}, 0);

    print_table_header(oss, "Counter properties");
    print_table_contents(oss, parts);
    print_table_footer(oss);
}

int main(int argc, char **argv)
{
    std::ofstream oss("/home/florian/src/mesytec-docs/nuclear_physics/mvlc/trigger_io_tables.tex");

    fmt::println(oss, "% Generated by the mvlc_trigger_io_tool from the mesytec-mvlc driver library.");

    gen_timer_table(oss);
    gen_nim_io_table(oss);
    gen_ecl_io_table(oss);
    gen_trigger_resource_table(oss);
    gen_stackbusy_table(oss);
    gen_lut_table(oss);
    gen_stackstart_table(oss);
    gen_synctrigger_table(oss);
    gen_counter_table(oss);

    return 0;
}
